import {
  DailyProduction,
  ExpenseRecord,
  InventoryItem,
  PoultryHouse,
  SalesOrder,
  User,
  Customer
} from '../types';

export const DEFAULT_USER: User = {
  id: 'usr_arisadumri',
  email: 'arisadumri@gmail.com',
  name: 'คุณอริสา ดำริ (Arisa Damri)',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  role: 'owner',
  farmName: 'ฟาร์มไก่นำโชค สำนักงานใหญ่ (ชลบุรี)',
  serverName: 'Ari Server',
  lastLogin: new Date().toISOString(),
};

export const INITIAL_HOUSES: PoultryHouse[] = [
  {
    id: 'house-a1',
    name: 'โรงเรือน A1 (ปิด Evap)',
    flockCode: 'FLOCK-2026-A1',
    breed: 'โรมานน์บราวน์ (Lohmann Brown)',
    initialHenCount: 10000,
    currentHenCount: 9780,
    ageWeeks: 34,
    housedDate: '2025-12-15',
    status: 'active',
  },
  {
    id: 'house-a2',
    name: 'โรงเรือน A2 (ปิด Evap)',
    flockCode: 'FLOCK-2026-A2',
    breed: 'ซีพี บราวน์ (CP Brown)',
    initialHenCount: 12000,
    currentHenCount: 11840,
    ageWeeks: 28,
    housedDate: '2026-01-20',
    status: 'active',
  },
  {
    id: 'house-b1',
    name: 'โรงเรือน B1 (ปิด Evap)',
    flockCode: 'FLOCK-2025-B1',
    breed: 'ไฮไลน์บราวน์ (Hy-Line Brown)',
    initialHenCount: 8500,
    currentHenCount: 8120,
    ageWeeks: 58,
    housedDate: '2025-06-10',
    status: 'active',
  },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'cust-1',
    name: 'ตลาดสดยิ่งเจริญ (ร้านเจ๊พรไข่สด)',
    contactPerson: 'คุณสมพร',
    phone: '081-456-7890',
    address: 'โซนขายส่ง แผง 42 ตลาดยิ่งเจริญ สะพานใหม่ กทม.',
    taxId: '0105558012345',
    customerType: 'wholesale',
  },
  {
    id: 'cust-2',
    name: 'บริษัท เบเกอรี่ ดีไลท์ จำกัด',
    contactPerson: 'คุณธนภัทร',
    phone: '02-998-1122',
    address: '88/14 นิคมอุตสาหกรรมบางพลี จ.สมุทรปราการ',
    taxId: '0105561088992',
    customerType: 'supermarket',
  },
  {
    id: 'cust-3',
    name: 'ร้านอาหารเรือนทอง & คาเฟ่',
    contactPerson: 'คุณวิภาดา',
    phone: '089-223-9988',
    address: '124 ถนนสุขุมวิท ต.เสม็ด อ.เมือง จ.ชลบุรี',
    customerType: 'restaurant',
  },
  {
    id: 'cust-4',
    name: 'สหกรณ์การเกษตรและร้านค้าชุมชน',
    contactPerson: 'ลุงประสิทธิ์',
    phone: '086-778-3344',
    address: 'หมู่ 4 ต.หนองรี อ.เมือง จ.ชลบุรี',
    customerType: 'retail',
  },
];

export const INITIAL_PRODUCTIONS: DailyProduction[] = [
  {
    id: 'prod-001',
    date: '2026-08-24',
    houseId: 'house-a1',
    houseName: 'โรงเรือน A1 (ปิด Evap)',
    grades: {
      jumbo: 480,
      grade0: 1850,
      grade1: 3200,
      grade2: 2450,
      grade3: 1100,
      grade4: 220,
      damaged: 45,
    },
    totalCollected: 9345,
    mortalityCount: 3,
    cullCount: 1,
    feedConsumedKg: 1120,
    waterConsumedLiters: 2600,
    layingRatePercent: 95.55,
    notes: 'ไก่สมบูรณ์ดี อัตราไข่สูงสม่ำเสมอ คุณภาพเปลือกไข่หนาแน่น',
    recordedBy: 'คุณอริสา ดำริ',
    createdAt: '2026-08-24T08:30:00.000Z',
  },
  {
    id: 'prod-002',
    date: '2026-08-24',
    houseId: 'house-a2',
    houseName: 'โรงเรือน A2 (ปิด Evap)',
    grades: {
      jumbo: 550,
      grade0: 2400,
      grade1: 4100,
      grade2: 2800,
      grade3: 1250,
      grade4: 180,
      damaged: 38,
    },
    totalCollected: 11318,
    mortalityCount: 2,
    cullCount: 0,
    feedConsumedKg: 1360,
    waterConsumedLiters: 3100,
    layingRatePercent: 95.59,
    notes: 'รุ่นสาวพีคโปรดักชั่น ไข่เบอร์ 1 และ 0 สวยมาก',
    recordedBy: 'คุณอริสา ดำริ',
    createdAt: '2026-08-24T08:45:00.000Z',
  },
  {
    id: 'prod-003',
    date: '2026-08-24',
    houseId: 'house-b1',
    houseName: 'โรงเรือน B1 (ปิด Evap)',
    grades: {
      jumbo: 980,
      grade0: 2200,
      grade1: 2150,
      grade2: 1300,
      grade3: 420,
      grade4: 80,
      damaged: 55,
    },
    totalCollected: 7185,
    mortalityCount: 5,
    cullCount: 2,
    feedConsumedKg: 980,
    waterConsumedLiters: 2200,
    layingRatePercent: 88.48,
    notes: 'ไก่รุ่นอายุ 58 สัปดาห์ ไข่จัมโบ้และเบอร์ 0 ปริมาณมาก',
    recordedBy: 'ช่างสมชาย (ผู้ช่วยดูแล)',
    createdAt: '2026-08-24T09:00:00.000Z',
  },
];

export const INITIAL_ORDERS: SalesOrder[] = [
  {
    id: 'ord-001',
    invoiceNumber: 'KNC-INV-20260824-001',
    customerId: 'cust-1',
    customerName: 'ตลาดสดยิ่งเจริญ (ร้านเจ๊พรไข่สด)',
    customerPhone: '081-456-7890',
    customerAddress: 'โซนขายส่ง แผง 42 ตลาดยิ่งเจริญ สะพานใหม่ กทม.',
    date: '2026-08-24',
    items: [
      {
        id: 'item-1',
        type: 'egg_tray',
        name: 'ไข่ไก่สดคละเกรด คัดพิเศษ เบอร์ 0',
        grade: 'grade0',
        quantity: 120, // 120 แผง = 3,600 ฟอง
        unit: 'แผง (30 ฟอง)',
        unitPrice: 135,
        totalPrice: 16200,
      },
      {
        id: 'item-2',
        type: 'egg_tray',
        name: 'ไข่ไก่สดคละเกรด คัดพิเศษ เบอร์ 1',
        grade: 'grade1',
        quantity: 180, // 180 แผง = 5,400 ฟอง
        unit: 'แผง (30 ฟอง)',
        unitPrice: 126,
        totalPrice: 22680,
      },
      {
        id: 'item-3',
        type: 'egg_tray',
        name: 'ไข่ไก่สดคละเกรด คัดพิเศษ เบอร์ 2',
        grade: 'grade2',
        quantity: 100, // 100 แผง = 3,000 ฟอง
        unit: 'แผง (30 ฟอง)',
        unitPrice: 117,
        totalPrice: 11700,
      }
    ],
    subtotal: 50580,
    discount: 580,
    vat: 0,
    grandTotal: 50000,
    paymentMethod: 'transfer',
    paymentStatus: 'paid',
    deliveryStatus: 'delivered',
    soldBy: 'คุณอริสา ดำริ',
    notes: 'ส่งด้วยรถควบคุมอุณหภูมิ KNC-01 รอบเช้า',
    createdAt: '2026-08-24T10:15:00.000Z',
  },
  {
    id: 'ord-002',
    invoiceNumber: 'KNC-INV-20260824-002',
    customerId: 'cust-2',
    customerName: 'บริษัท เบเกอรี่ ดีไลท์ จำกัด',
    customerPhone: '02-998-1122',
    customerAddress: '88/14 นิคมอุตสาหกรรมบางพลี จ.สมุทรปราการ',
    date: '2026-08-24',
    items: [
      {
        id: 'item-4',
        type: 'egg_tray',
        name: 'ไข่ไก่สดคละเกรด เบอร์ 2 (สำหรับโรงงานทำขนม)',
        grade: 'grade2',
        quantity: 250,
        unit: 'แผง (30 ฟอง)',
        unitPrice: 115,
        totalPrice: 28750,
      },
      {
        id: 'item-5',
        type: 'egg_tray',
        name: 'ไข่ไก่สด จัมโบ้ (พรีเมียม)',
        grade: 'jumbo',
        quantity: 40,
        unit: 'แผง (30 ฟอง)',
        unitPrice: 145,
        totalPrice: 5800,
      }
    ],
    subtotal: 34550,
    discount: 0,
    vat: 0,
    grandTotal: 34550,
    paymentMethod: 'credit',
    paymentStatus: 'pending',
    deliveryStatus: 'shipping',
    soldBy: 'คุณอริสา ดำริ',
    notes: 'เครดิตเทอม 15 วัน',
    createdAt: '2026-08-24T11:40:00.000Z',
  },
];

export const INITIAL_INVENTORY: InventoryItem[] = [
  {
    id: 'inv-egg-jumbo',
    code: 'EGG-JB',
    name: 'ไข่ไก่พรีเมียม จัมโบ้ (>70g)',
    category: 'eggs',
    grade: 'jumbo',
    currentStock: 1800,
    unit: 'ฟอง',
    minThreshold: 500,
    unitCost: 3.8,
    lastUpdated: '2026-08-24T09:00:00.000Z',
  },
  {
    id: 'inv-egg-0',
    code: 'EGG-G0',
    name: 'ไข่ไก่ เบอร์ 0 (70-74g)',
    category: 'eggs',
    grade: 'grade0',
    currentStock: 4500,
    unit: 'ฟอง',
    minThreshold: 1500,
    unitCost: 3.5,
    lastUpdated: '2026-08-24T09:00:00.000Z',
  },
  {
    id: 'inv-egg-1',
    code: 'EGG-G1',
    name: 'ไข่ไก่ เบอร์ 1 (65-69g)',
    category: 'eggs',
    grade: 'grade1',
    currentStock: 6800,
    unit: 'ฟอง',
    minThreshold: 2000,
    unitCost: 3.2,
    lastUpdated: '2026-08-24T09:00:00.000Z',
  },
  {
    id: 'inv-egg-2',
    code: 'EGG-G2',
    name: 'ไข่ไก่ เบอร์ 2 (60-64g)',
    category: 'eggs',
    grade: 'grade2',
    currentStock: 5200,
    unit: 'ฟอง',
    minThreshold: 1500,
    unitCost: 2.9,
    lastUpdated: '2026-08-24T09:00:00.000Z',
  },
  {
    id: 'inv-feed-layer',
    code: 'FEED-L92',
    name: 'อาหารสำเร็จรูปไก่ไข่ระยะให้ไข่ (โปรตีน 17.5%)',
    category: 'feed',
    currentStock: 420,
    unit: 'กระสอบ (30 กก.)',
    minThreshold: 100,
    unitCost: 440,
    lastUpdated: '2026-08-24T08:00:00.000Z',
  },
  {
    id: 'inv-feed-corn',
    code: 'FEED-CRN',
    name: 'ข้าวโพดเลี้ยงสัตว์บดหยาบ คุณภาพพิเศษ',
    category: 'feed',
    currentStock: 150,
    unit: 'กระสอบ (50 กก.)',
    minThreshold: 50,
    unitCost: 550,
    lastUpdated: '2026-08-23T16:00:00.000Z',
  },
  {
    id: 'inv-tray-paper',
    code: 'PKG-TRAY30',
    name: 'แผงไข่กระดาษรีไซเคิล 30 ฟอง ตราไก่นำโชค',
    category: 'packaging',
    currentStock: 2500,
    unit: 'แผง',
    minThreshold: 800,
    unitCost: 2.8,
    lastUpdated: '2026-08-24T07:30:00.000Z',
  },
  {
    id: 'inv-med-vit',
    code: 'MED-VITA-PLUS',
    name: 'วิตามินรวมละลายน้ำ + อิเล็กโทรไลต์ สูตรไข่ดก',
    category: 'medicine',
    currentStock: 45,
    unit: 'ซอง (1 กก.)',
    minThreshold: 15,
    unitCost: 280,
    lastUpdated: '2026-08-20T10:00:00.000Z',
  },
];

export const INITIAL_EXPENSES: ExpenseRecord[] = [
  {
    id: 'exp-001',
    date: '2026-08-22',
    category: 'feed',
    title: 'สั่งซื้อหัวอาหารไก่ไข่ 200 กระสอบ',
    amount: 88000,
    paidTo: 'บริษัท อาหารสัตว์สยาม จำกัด',
    recordedBy: 'คุณอริสา ดำริ',
    receiptNumber: 'REC-FEED-88219',
    notes: 'ส่งมอบครบถ้วนเข้าโกดังอาหาร 1',
  },
  {
    id: 'exp-002',
    date: '2026-08-20',
    category: 'utility',
    title: 'ค่ากระแสไฟฟ้า โรงเรือน Evap 3 หลัง ประจำเดือน',
    amount: 24500,
    paidTo: 'การไฟฟ้านครหลวง/ส่วนภูมิภาค',
    recordedBy: 'คุณอริสา ดำริ',
    receiptNumber: 'PEA-77881920',
  },
  {
    id: 'exp-003',
    date: '2026-08-18',
    category: 'medicine_vaccine',
    title: 'วัคซีนนิวคาสเซิลและหลอดลมอักเสบติดต่อ พร้อมวิตามินบำรุง',
    amount: 9800,
    paidTo: 'คลินิกสัตวแพทย์เกษตรพัฒนา',
    recordedBy: 'คุณอริสา ดำริ',
    notes: 'ฉีดพ่นและละลายน้ำตามตารางสัตวบาล',
  },
  {
    id: 'exp-004',
    date: '2026-08-15',
    category: 'packaging',
    title: 'สั่งพิมพ์แผงกระดาษไข่ไก่ 5,000 แผง ตราไก่นำโชค',
    amount: 14000,
    paidTo: 'โรงงานบรรจุภัณฑ์รุ่งเรือง',
    recordedBy: 'คุณอริสา ดำริ',
  },
];
